version: '2'
services:
    questprova-app:
        image: questprova
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://questprova-mysql:3306/questprova?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    questprova-mysql:
        extends:
            file: mysql.yml
            service: questprova-mysql
